name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md' # ignore changes to readmes
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i
      - name: Run tests
        run: bun test:nested
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          